### ISSUE TITLE
Fuzzy Search Functionality

### ISSUE THREAD

**Issue by soniyaprasad77** [Hashnode/awesome-docs-gallery#27]
## Background 
While we search for keywords such as "reactjs", "react.js" which are widely used aliases for react. We donot get to see any results due to the current logic where it checks for string includes in title and description.

|  With reactjs |  With react |
| ------------- |:-------------:|
|    ![Screenshot (491)](https://github.com/user-attachments/assets/9d103a6c-8334-4371-b3f0-c57a7b2d74e6) |  ![Screenshot (493)](https://github.com/user-attachments/assets/96fefe3c-8b87-433f-8307-5bbdf391f86b) |

## Proposed Solution 
To overcome this sort of behaviour, an alternative that is available is Fuzzy Search. I would like to implement it with help of [fusejs.io](https://www.fusejs.io/), What are your thoughts on this?

**Comment by jomefavourite** [comment]
Hello, @soniyaprasad77. Thanks for spotting this issue with the project. However, using [fusejs.io](https://www.fusejs.io/) might complicate things, and we'd like to keep things simple.
